apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaservice
  template:
    metadata:
      labels:
        app: kafkaservice
    spec:
      containers:
        - name: kafkaservice
          image: sibendu/kafkaservice
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_HOST
              value: kafka-service
            - name: KAFKA_PORT
              value: "9092"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaservice
spec:
  type: NodePort
  selector:
    app: kafkaservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090     